### ISSUE TITLE
create ArtifactFormat version 7.0

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#747]
Add items to include here. (Some updates on 3 Dec 2024)

- [ ] cpu architecture and flags
- [x] conda environment info, if available
- [x] file size of each input artifact
- [x] forward compatibility marker of some sort (see semantic versioning discussion below) 
- [ ] support for integrating the following types of annotations (e.g., an `annotations` directory)
  - [x] @gregcaporaso and @ebolyen talked about adding arbitrary notes named something like note-001.md, note-002.md, ..., note-999.md. some reasonable limit would need to be placed on file size for each of these. 
  - [ ] support for adding a data license
  - [ ] support for including a source and/or creator
  - [ ] support for signing

**Comment by lizgehret** [comment]
Okay some initial thoughts/questions:

In the top-level dir, we can include a new file with the following info (if available) that we can call something like `env_arch_info.txt`:
- conda env info (what would we like to include? version of conda? QIIME 2 version/distro?)
- CPU arch & flags (just four main flags, if available?)

It probably makes sense to include the input artifact(s) file size within the provenance (but am open to other opinions on this).

What exactly are we thinking re: forward compatibility marker? Like what version(s) of QIIME 2 this artifact is compatible with?

For annotations support - since these don't currently exist, this would then just be adding that `annotations` dir in the top level artifact dir?

I'm thinking for license, we just add our full license file in the top level dir (and we can have a centralized location for this, maybe AWS? where we can keep track of any updates (i.e. years on the header, or any actual content changes)

What are we thinking for source and/or creator? As in, the user who created the artifact?

cc @gregcaporaso @ebolyen

**Comment by ebolyen** [comment]
> In the top-level dir, we can include a new file with the following info (if available) that we can call something like env_arch_info.txt:

>    conda env info (what would we like to include? version of conda? QIIME 2 version/distro?)
     CPU arch & flags (just four main flags, if available?)

I was thinking it would go in the `environment` section of `action.yaml`

```yaml
environment:
    platform: macosx-10.9-x86_64
    cpu: <flags here>
    python: |-
        3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:53:34) [Clang 16.0.6 ]
    framework:
        version: 2024.10.1
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2024.10.1|0'
    plugins:
        phylogeny:
            version: 2024.10.0
            website: https://github.com/qiime2/q2-phylogeny
    conda-packages:
       <so many...>
    python-packages:
        Brotli: 1.1.0
        DendroPy: 5.0.1
        MarkupSafe: 3.0.2
```

But I think maybe creating a `conda env export` and placing that file (build numbers included) under the prov directory may end up being a little bit more useful.

> It probably makes sense to include the input artifact(s) file size within the provenance (but am open to other opinions on this).

I think this will happen recursively because we will measure the /data/ directory when the artifact is made, and so it will have the provenance with the file size.

As for where we put it, I'm not sure. Maybe it should look like the checksums file? That would make things kind of easy. We could also just have a property like `output-size: 6210` (6.2kb) under the `action` section of `action.yaml`. This would be analagous to `output-name: 'foo'`.

> What exactly are we thinking re: forward compatibility marker? Like what version(s) of QIIME 2 this artifact is compatible with?

We could use semver, like this could be `7.0` and we indicate forward compatibility from this point via the major version. So q2 2025.5 would read `7.0`, `7.1`, etc, but would throw the unpopular error on `8.0`.

> For annotations support - since these don't currently exist, this would then just be adding that annotations dir in the top level artifact dir?

I've no idea to be honest. There's also the problem of UUID. I think it's a bit more useful to annotate on the same UUID so it probably would look like a directory or something. In the event we wanted a new UUID, then we need to create an alias and this looks like an action type (like "import" but "annotate" or something)

> I'm thinking for license, we just add our full license file in the top level dir (and we can have a centralized location for this, maybe AWS? where we can keep track of any updates (i.e. years on the header, or any actual content changes)

I think this is more of for the data itself. So I suspect it's part of annotation. i.e. I used a proprietary database or something like GISAID

> What are we thinking for source and/or creator? As in, the user who created the artifact?

Probably, maybe this looks like a what git does with a commit author, but how do we want to identify a user persistently (do we want to?), and do we have any goals with crypto signatures (like a signed commit)
