### ISSUE TITLE
require plugin name when specifying parallel Executor mappings

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#802]
Currently only the action name is required, which may become a problem if different plugins define actions with the same name. 

So, an executor mapping like the following:

```python
em = {'summarize': 'tpool'}
```

or 

```toml
[parsl.executor_mapping]
summarize = "tpool"
```

would become something like:

```python
em = {'feature-table.summarize': 'tpool'}
```

or 

```toml
[parsl.executor_mapping]
feature-table.summarize = "tpool"
```
